export const SET_REPOSITORIES_ARRAY = 'SET_REPOSITORIES_ARRAY';

export const SET_OWNER_DATA = 'SET_OWNER_DATA';

export const SET_LANGUAGES_ARRAY = 'SET_LANGUAGES_ARRAY';

export const SET_SELECTED_LANGUAGES = 'SET_SELECTED_LANGUAGES';

export const SET_ORDERING_TYPE = 'SET_ORDERING_TYPE';
